#!/usr/bin/env python3
"""
End-to-end integration test for constitution enforcement flow.
Tests: tasks.md → orchestrator → executor → watchdog → checkpoint validation
"""

import json
import subprocess
import sys
import tempfile
import shutil
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Pytest fixture — builds the full environment once per test
# ---------------------------------------------------------------------------

@pytest.fixture()
def test_dir():
    """Create a fully-populated temp directory for constitution tests."""
    d = tempfile.mkdtemp(prefix="constitution_test_")

    # Create required directories
    (Path(d) / ".claude").mkdir()
    (Path(d) / "memory-bank" / "shared").mkdir(parents=True)
    (Path(d) / "src").mkdir()

    # Initialize git repo
    subprocess.run(["git", "init"], cwd=d, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=d, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=d, capture_output=True)

    # Create initial commit
    (Path(d) / "README.md").write_text("# Test Project\n")
    subprocess.run(["git", "add", "."], cwd=d, capture_output=True)
    subprocess.run(["git", "commit", "-m", "Initial commit"], cwd=d, capture_output=True)

    # Constitution
    constitution_path = Path(d) / "memory-bank" / "shared" / ".constitution.md"
    constitution_path.write_text("""# Project Constitution

## Code Standards

- All Python functions must have type hints for parameters and return values
- All Python functions must have docstrings describing their purpose

## Security Standards

- No hardcoded API keys, passwords, or tokens allowed in source code
- Use environment variables or secure vaults for secrets

## Testing Standards

- All new Python files must have corresponding test files
- Maintain minimum 80% test coverage for new code
""")

    # tasks.md
    (Path(d) / "tasks.md").write_text("""# Test Tasks

- [ ] Create a utility module `src/utils.py`
  - **Constitution**: TYPE_HINTS_REQUIRED, DOCSTRINGS_REQUIRED
  - **Files**: `src/utils.py`
""")

    # Run orchestrator
    cli_dir = Path(__file__).parent.parent / "cli"
    cmd = [
        sys.executable,
        str(cli_dir / "orchestrator.py"),
        "--tasks-file", str(Path(d) / "tasks.md"),
        "--phase-id", "TEST",
    ]
    subprocess.run(cmd, cwd=d, capture_output=True)

    # Create violating file and stage it
    (Path(d) / "src" / "utils.py").write_text("""# Utility module

def calculate_sum(a, b):
    return a + b

def get_credentials():
    # Violates NO_HARDCODED_SECRETS
    api_key = "sk-1234567890abcdef"
    return api_key
""")
    subprocess.run(["git", "add", "src/utils.py"], cwd=d, capture_output=True)

    yield d

    shutil.rmtree(d)


# ---------------------------------------------------------------------------
# Pytest tests
# ---------------------------------------------------------------------------

def test_orchestrator_embeds_constitution_rules(test_dir):
    """Orchestrator must propagate constitution rules into execution_plan.json."""
    plan_file = Path(test_dir) / "execution_plan.json"
    assert plan_file.exists(), "execution_plan.json not generated by orchestrator"

    plan = json.loads(plan_file.read_text())
    found_rules = any(
        task.get("constitution_rules")
        for wave in plan["execution_plan"]["waves"]
        for task in wave["tasks"]
    )
    assert found_rules, "No constitution_rules found in any task inside execution_plan.json"


def test_constitution_validation(test_dir):
    """Constitution.validate_output() must detect type-hint, docstring, and secret violations."""
    cli_dir = Path(__file__).parent.parent / "cli"
    sys.path.insert(0, str(cli_dir))

    from constitution_parser import Constitution

    constitution_path = Path(test_dir) / "memory-bank" / "shared" / ".constitution.md"
    constitution = Constitution(str(constitution_path))

    result = subprocess.run(
        ["git", "diff", "--name-only", "--cached"],
        cwd=test_dir,
        capture_output=True,
        text=True,
    )
    modified_files = [
        Path(test_dir) / f
        for f in result.stdout.strip().split("\n")
        if f
    ]

    violations = constitution.validate_output(modified_files)
    assert violations, "Constitution validation found no violations — detection logic broken"

    found_violations = {v.rule for v in violations}
    expected = {"TYPE_HINTS_REQUIRED", "DOCSTRINGS_REQUIRED", "NO_HARDCODED_SECRETS"}
    missing = expected - found_violations
    assert not missing, f"Expected violations not detected: {missing}"


# ---------------------------------------------------------------------------
# Standalone runner (kept for direct execution)
# ---------------------------------------------------------------------------

def main():
    """Run as standalone script via pytest."""
    return pytest.main([__file__, "-v"])


if __name__ == "__main__":
    sys.exit(main())
