#!/usr/bin/env python3
"""
Micro-Checkpoint: Frequent git commits to stay in Ralph smart zone
Commits after every logical change, not just wave completion.
"""

import subprocess
import sys
from pathlib import Path
from datetime import datetime

def has_uncommitted_changes() -> bool:
    """Check if there are uncommitted changes"""
    result = subprocess.run(
        ['git', 'status', '--porcelain'],
        capture_output=True,
        text=True
    )
    return bool(result.stdout.strip())

def get_changed_files() -> list[str]:
    """Get list of changed files"""
    result = subprocess.run(
        ['git', 'status', '--porcelain'],
        capture_output=True,
        text=True
    )
    files = []
    for line in result.stdout.split('\n'):
        if line.strip():
            # Format: " M file.py" or "?? file.py"
            parts = line.strip().split(maxsplit=1)
            if len(parts) == 2:
                files.append(parts[1])
    return files

def create_micro_checkpoint(message: str = None, auto: bool = False) -> bool:
    """
    Create a micro-checkpoint (frequent git commit).
    
    Args:
        message: Optional commit message
        auto: If True, auto-generate message from changed files
    
    Returns:
        True if checkpoint created, False if no changes
    """
    if not has_uncommitted_changes():
        print("   ℹ️  No changes to commit")
        return False
    
    # Get changed files for auto message
    changed_files = get_changed_files()
    
    # Generate message if auto
    if auto and not message:
        if len(changed_files) == 1:
            message = f"Update {changed_files[0]}"
        elif len(changed_files) <= 3:
            message = f"Update {', '.join(changed_files)}"
        else:
            message = f"Update {len(changed_files)} files"
    
    if not message:
        message = f"Micro-checkpoint {datetime.now().strftime('%H:%M:%S')}"
    
    # Stage all changes
    subprocess.run(['git', 'add', '.'], check=True)
    
    # Create commit
    commit_msg = f"""[MICRO-CHECKPOINT] {message}

{datetime.now().isoformat()}
Generated by: dev-kid micro-checkpoint
Files: {', '.join(changed_files[:5])}{'...' if len(changed_files) > 5 else ''}

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"""
    
    subprocess.run(
        ['git', 'commit', '-m', commit_msg],
        check=True,
        capture_output=True
    )
    
    # Get commit hash
    result = subprocess.run(
        ['git', 'rev-parse', '--short', 'HEAD'],
        capture_output=True,
        text=True,
        check=True
    )
    commit_hash = result.stdout.strip()
    
    print(f"   ✅ Micro-checkpoint: {commit_hash}")
    print(f"      {message}")
    
    return True

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Create micro-checkpoint (frequent git commit for Ralph smart zone)"
    )
    parser.add_argument('message', nargs='?', help='Commit message')
    parser.add_argument('--auto', action='store_true',
                       help='Auto-generate message from changed files')
    
    args = parser.parse_args()
    
    if not create_micro_checkpoint(args.message, args.auto):
        sys.exit(1)

if __name__ == "__main__":
    main()
