#!/usr/bin/env python3
"""
Micro-Checkpoint: Frequent git commits to stay in Ralph smart zone
Commits after every logical change, not just wave completion.
"""

import os
import subprocess
import sys
from datetime import datetime


# Generated artifacts that must never enter a checkpoint commit. Override with
# DEV_KID_CHECKPOINT_EXCLUDES (colon-separated git pathspecs); set
# DEV_KID_CHECKPOINT_ALL=true to restore blanket staging.
# NOTE: directory patterns need a trailing /* — a bare "*.egg-info" pathspec
# does NOT exclude files nested inside it.
DEFAULT_CHECKPOINT_EXCLUDES = [
    ".claude/session_snapshots/*",
    ".claude/activity_stream.md",
    ".claude/AGENT_STATE.json",
    ".claude/system_bus.json",
    ".claude/task_timers.json",
    "memory-bank/private/*",
    "*.egg-info/*",
    "*__pycache__/*",
    "*.pyc",
    "*.pyo",
]


def exclude_pathspecs() -> list:
    """Build git :(exclude) pathspecs for generated artifacts."""
    if os.environ.get("DEV_KID_CHECKPOINT_ALL", "false").lower() == "true":
        return []
    raw = os.environ.get("DEV_KID_CHECKPOINT_EXCLUDES")
    patterns = [p for p in raw.split(":") if p] if raw else DEFAULT_CHECKPOINT_EXCLUDES
    return [f":(exclude){p}" for p in patterns]


def has_uncommitted_changes() -> bool:
    """Check if there are uncommitted changes"""
    result = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True
    )
    return bool(result.stdout.strip())


def get_changed_files() -> list[str]:
    """Get list of changed files"""
    result = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True
    )
    files = []
    for line in result.stdout.split("\n"):
        if line.strip():
            # Format: " M file.py" or "?? file.py"
            parts = line.strip().split(maxsplit=1)
            if len(parts) == 2:
                files.append(parts[1])
    return files


def create_micro_checkpoint(message: str = None, auto: bool = False) -> bool:
    """
    Create a micro-checkpoint (frequent git commit).

    Args:
        message: Optional commit message
        auto: If True, auto-generate message from changed files

    Returns:
        True if checkpoint created, False if no changes
    """
    if not has_uncommitted_changes():
        print("   ℹ️  No changes to commit")
        return False

    # Get changed files for auto message
    changed_files = get_changed_files()

    # Generate message if auto
    if auto and not message:
        if len(changed_files) == 1:
            message = f"Update {changed_files[0]}"
        elif len(changed_files) <= 3:
            message = f"Update {', '.join(changed_files)}"
        else:
            message = f"Update {len(changed_files)} files"

    if not message:
        message = f"Micro-checkpoint {datetime.now().strftime('%H:%M:%S')}"

    # Stage changes, EXCLUDING generated artifacts (see skills/checkpoint.sh
    # for the rationale). Blanket `git add .` used to sweep build output and
    # dev-kid's own session state into every checkpoint commit.
    subprocess.run(["git", "add", "-A", "--", "."] + exclude_pathspecs(), check=True)

    # Create commit
    commit_msg = f"""[MICRO-CHECKPOINT] {message}

{datetime.now().isoformat()}
Generated by: dev-kid micro-checkpoint
Files: {', '.join(changed_files[:5])}{'...' if len(changed_files) > 5 else ''}

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"""

    subprocess.run(["git", "commit", "-m", commit_msg], check=True, capture_output=True)

    # Get commit hash
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    commit_hash = result.stdout.strip()

    print(f"   ✅ Micro-checkpoint: {commit_hash}")
    print(f"      {message}")

    return True


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Create micro-checkpoint (frequent git commit for Ralph smart zone)"
    )
    parser.add_argument("message", nargs="?", help="Commit message")
    parser.add_argument(
        "--auto", action="store_true", help="Auto-generate message from changed files"
    )

    args = parser.parse_args()

    if not create_micro_checkpoint(args.message, args.auto):
        sys.exit(1)


if __name__ == "__main__":
    main()
