#!/usr/bin/env bash
# Skill: Create Checkpoint
# Trigger: "checkpoint", context >80%, session end

set -e

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
    MESSAGE="Checkpoint - $(date +%Y-%m-%d\ %H:%M:%S)"
fi

echo "📸 Creating checkpoint: $MESSAGE"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sync memory first
if [ -f "$SCRIPT_DIR/sync_memory.sh" ]; then
    "$SCRIPT_DIR/sync_memory.sh"
fi

# Stage all changes
git add .

# Check if there are changes to commit
if git diff --cached --quiet; then
    echo "   ℹ️  No changes to commit"
    exit 0
fi

# Create commit
COMMIT_MSG="[CHECKPOINT] $MESSAGE

$(date)
Generated by: dev-kit checkpoint skill

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"

COMMIT_HASH=$(git rev-parse --short HEAD)
echo "✅ Checkpoint created: $COMMIT_HASH"
