#!/usr/bin/env bash
# Skill: Create Checkpoint
# Trigger: "checkpoint", context >80%, session end

set -e

# Helper function to find skills
find_skill() {
    local skill_name="$1"
    local search_paths=(
        "$SCRIPT_DIR/$skill_name"
        "${DEV_KID_ROOT:-$HOME/.dev-kid}/skills/$skill_name"
    )
    for path in "${search_paths[@]}"; do
        if [ -f "$path" ] && [ -x "$path" ]; then
            echo "$path"
            return 0
        fi
    done
    return 1
}

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
    MESSAGE="Checkpoint - $(date +%Y-%m-%d\ %H:%M:%S)"
fi

echo "📸 Creating checkpoint: $MESSAGE"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sync memory first
if sync_memory=$(find_skill "sync_memory.sh" 2>/dev/null); then
    "$sync_memory"
fi

# ------------------------------------------------------------------
# Refuse to auto-commit from inside a LINKED git worktree.
#
# Agent sessions routinely share one dev-kid-tracked repo via
# `git worktree add` — each session gets its own isolated branch and
# working directory. This script is a TRACKED file, so every worktree
# inherits it, and a session's own checkpoint would otherwise land a
# generic "[CHECKPOINT] ..." commit on that worktree's branch — noise
# the branch owner never asked for, on a branch that is often meant to
# hold only that session's own intentional commits.
#
# Detection: a linked worktree's `git rev-parse --git-dir` (the
# worktree-specific gitdir under .git/worktrees/<name>) differs from
# `--git-common-dir` (the shared repo's real .git); in the main
# checkout the two resolve to the same path.
#
# Override: DEV_KID_ALLOW_WORKTREE_COMMIT=true restores the old
# always-commit behavior inside a worktree.
# ------------------------------------------------------------------
_devkid_in_linked_worktree() {
    local git_dir common_dir
    git_dir=$(git rev-parse --git-dir 2>/dev/null) || return 1
    common_dir=$(git rev-parse --git-common-dir 2>/dev/null) || return 1
    git_dir=$(cd "$git_dir" 2>/dev/null && pwd -P) || return 1
    common_dir=$(cd "$common_dir" 2>/dev/null && pwd -P) || return 1
    [ "$git_dir" != "$common_dir" ]
}

if _devkid_in_linked_worktree && [ "${DEV_KID_ALLOW_WORKTREE_COMMIT:-false}" != "true" ]; then
    echo "   ℹ️  Linked git worktree detected — skipping git commit (checkpoint.sh never auto-commits inside a worktree)"
    echo "      Override with DEV_KID_ALLOW_WORKTREE_COMMIT=true if you really want to commit here"
    exit 0
fi

# ------------------------------------------------------------------
# Stage changes — EXCLUDING generated artifacts.
#
# This used to be a blanket `git add .`, which swept build output and
# dev-kid's own session state into every checkpoint commit: .egg-info,
# __pycache__/*.pyc, .claude/ session snapshots + activity stream, and
# memory-bank/private. Those commits then made merged branches look
# unmerged and polluted diffs.
#
# Override the list with DEV_KID_CHECKPOINT_EXCLUDES (colon-separated
# git pathspecs). Set DEV_KID_CHECKPOINT_ALL=true to restore the old
# stage-everything behaviour.
#
# NOTE: directory patterns need a trailing /* — a bare `*.egg-info`
# pathspec does NOT exclude files nested inside it.
# ------------------------------------------------------------------
DEFAULT_EXCLUDES=".claude/session_snapshots/*:.claude/activity_stream.md:.claude/AGENT_STATE.json:.claude/system_bus.json:.claude/task_timers.json:memory-bank/private/*:*.egg-info/*:*__pycache__/*:*.pyc:*.pyo"

if [ "${DEV_KID_CHECKPOINT_ALL:-false}" = "true" ]; then
    git add -A .
else
    IFS=':' read -r -a _ex_patterns <<< "${DEV_KID_CHECKPOINT_EXCLUDES:-$DEFAULT_EXCLUDES}"
    _ex_args=()
    for _p in "${_ex_patterns[@]}"; do
        [ -n "$_p" ] && _ex_args+=(":(exclude)$_p")
    done
    git add -A -- . "${_ex_args[@]}"
fi

# Check if there are changes to commit
if git diff --cached --quiet; then
    echo "   ℹ️  No changes to commit"
    exit 0
fi

# Create commit
COMMIT_MSG="[CHECKPOINT] $MESSAGE

$(date)
Generated by: dev-kid checkpoint skill

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"

COMMIT_HASH=$(git rev-parse --short HEAD)
echo "✅ Checkpoint created: $COMMIT_HASH"
