#!/usr/bin/env bash
# Skill: Create Checkpoint
# Trigger: "checkpoint", context >80%, session end

set -e

# Helper function to find skills
find_skill() {
    local skill_name="$1"
    local search_paths=(
        "$SCRIPT_DIR/$skill_name"
        "${DEV_KID_ROOT:-$HOME/.dev-kid}/skills/$skill_name"
    )
    for path in "${search_paths[@]}"; do
        if [ -f "$path" ] && [ -x "$path" ]; then
            echo "$path"
            return 0
        fi
    done
    return 1
}

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
    MESSAGE="Checkpoint - $(date +%Y-%m-%d\ %H:%M:%S)"
fi

echo "📸 Creating checkpoint: $MESSAGE"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sync memory first
if sync_memory=$(find_skill "sync_memory.sh" 2>/dev/null); then
    "$sync_memory"
fi

# Stage all changes
git add .

# Check if there are changes to commit
if git diff --cached --quiet; then
    echo "   ℹ️  No changes to commit"
    exit 0
fi

# Create commit
COMMIT_MSG="[CHECKPOINT] $MESSAGE

$(date)
Generated by: dev-kid checkpoint skill

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"

COMMIT_HASH=$(git rev-parse --short HEAD)
echo "✅ Checkpoint created: $COMMIT_HASH"
